version: "3.8"
services:
  myqsl:
    image: lpedro7/mysqlforum
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
    restart: always
    container_name: mysql
    expose:
      - '3306'
    ports:
    - 3306:3306
  web:
    image: lpedro7/frontforum
    ports:
      - 3000:3000
    depends_on:
      - mysql
    restart: on-failure
  jdk:
    image: openjdk
    depends_on:
      - mysql
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
    - ./target:/app
    command: java -jar forum-0.0.1-SNAPSHOT.jar
    environment:
      - server.port=8080
      - token.expiration.time=1000000
      - token.secret="abcdefg"
      - spring.datasource.url=jdbc:mysql://mysql:3306/forum
      - spring.datasource.username=root
      - spring.datasource.password=root
      - images.url=http://localhost:8080
      - origins=http://localhost:3000